Close#4 Create first rest-controller
spasynkov/telegram-bot-insurance pull request #11
Opened 2020-10-23 17:37 UTC by babinvas

Close#4 Create first rest-controller

2020-10-24 23:56 UTC, spasynkov requested changes

2020-10-24 23:56 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/RController.java
> +    public RController() {
конструктор без параметров создается по умолчанию.
поскольку в этом классе нет других конструкторов - то и конструктор по умолчанию явно прописывать было не обязательно

2020-10-25 10:44 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/RController.java
> +    public RController() {
Да, знаю.
Но, я создал ещё конструктором (с парпаметром - на будущее).
Но, если это конструктор не нужен, я уберу.

2020-10-25 11:12 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/RController.java
> +    public RController() {
Да, знаю.
Видать я хотел создать ещё конструктор с параметром, да передумал, а удалить забыл.
Убераю.

2020-10-25 12:09 UTC, spasynkov commented
это был пробный контроллер, который в общую кодовую базу не пойдет.
поэтому пулл-риквест закрываю без мержа.
задачу сейчас тоже закрою.
важно было чтобы все разобрались с созданием контроллеров

2020-10-25 12:09 UTC, closed without merging