#3 accdb.test
spasynkov/telegram-bot-insurance pull request #16
Opened 2020-10-27 18:11 UTC by klimenkoMA

Close #3 
-created DB connection
-wrote tests for the database that check CRUD operations

2020-10-27 22:29 UTC, spasynkov requested changes
тесты надо немного переделать

2020-10-27 22:29 UTC, spasynkov commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=false
давайте в этом файле всегда оставлять одну пустую строку в конце. а то оно пишет потом, что в последней строке было изменение (добавился символ `\n`)

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public void fail() {
а зачем этот тест? если у джейюнита есть более удобный способ завалить тест, мы ж в телеге это на днях обсуждали с Георгием

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        Assertions.assertEquals(0, 1);
так у тебя все тесты, которые вдруг завалятся - будут иметь одну и ту же ошибку, что 0 не равно 1. согласись, не очень информативная ошибка :)

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        System.out.println("Begin destroying test object`s");
про принтелены - забудь) их больше не существует.
все пишем логгером (посмотри в переписке мы там обсуждали как логгер подключить)

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public static void destroyTestData(@Autowired UserRepository userRepos) {
почему не `userRepository`, как и раньше?

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        for (int i = 0; i < users.size(); i++) {
обрати внимание, у тебя в идее for должен быть подсвечен желтым (это значит, что тут ворнинг какой-то). поставь на него курсор и нажми Alt+Enter
на ворнинги всегда обращай внимание. они чаще всего делают код лучше

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        System.out.println("All test object`s destroyed");
снова же, заменить на логгер

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            }
абсолютно нетривиальный блок кода.
переписать через регулярку.

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            } catch (Exception ignored) {
если "проглатываешь" исключения - отлавливай только то, которое хочешь "проглотить", в твоем случае - NumberFormatException. это написано в джавадоках (если поставить курсор на метод `parseLong()` и нажать Ctrl+Q)

проблема в том, что если в этом блоке кода выскочит какое-то другое исключение (наследник _Exception_) - мы его точно так же "проглотим" и даже не будем знать, что у нас что-то сломалось. после того, как много дней подряд ты будешь искать почему программа работает, но не совсем так, как надо, и в итоге найдешь, что проблема была в этом - ты перестанешь так делать :)

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        List<User> userBefore = userRepository.findAll();
`userBefore` - не совсем удачное название переменной. я его читаю как "_пользователь ранее_". и когда я его дальше там увидел `userBefore.contains(user)` - я это прочитал как "_пользователь ранее содержит юзера? чеее?_"

лучше придумать название получше, типа, `usersListBeforeUserAdded`. не бойся длинных названий переменных. в спринге (в самой библиотеке) вообще с этим не заморачиваются.
посмотри вон [топ самых длинных названий классов в спринге](https://gist.github.com/thom-nic/2c74ed4075569da0f80b#file-output-txt) :) и это их не новички в программировании какие-то пишут.
в общем, главное - чтобы было понятно с первого взгляда на название что это и зачем

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        if (!userBefore.contains(user) & user.getName() != null || user.getEmail() != null) {
тут в одной строке больше всего вопросов:

- почему выбрал побитовое И вместо логического И?
- зачем проверять, что у юзера, которого ты чуть выше сам руками создал - не нулл-овые имя и имейл, если ты сам туда нулл-ы не ложил и никак с этим юзером еще не взаимодействовал? откуда там нулл-ам взяться? :)
- почему логическое ИЛИ? не будем заходить в этот иф только когда оба будут нулл-овые? типа, если одно из полей нулл - тогда все ок, можно продолжать?

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            List<User> usersAfter = userRepository.findAll();
переименовать аналогично предыдущему списку

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            }
тоже переписать через два ассершена:

- первым удостовериться, что список содержит юзера
- вторым удостовериться, что размер списка увеличился ровно на 1

7 строк твоего кода с иф-елсами заменить на две строчки ассершенов (читаемость кода повысится даже больше, чем в 3.5 раз)

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        }
и снова же, про принтелены забыть, фейл теста вручную не делать.
и вообще, вынести этот блок кода перед тем, как сохранять юзера. и тоже сделать через ассершен (ассертТру, или как-то так). тогда весь предыдущий блок кода можно будет писать не в елсе, а просто как продолжение метода (потому что если ассершен не сработает - то и дальше тест выполняться уже не будет)

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public void whenCalledSave_thenCorrectWriteNewUser() {
только после того, как я просмотрел весь метод - я понял что он делает. так не должно быть. должно быть понятно по названию, без заглядывания в код.
предлагаю поменять на что-то типа `whenCalledSave_thenNewUserSavedCorrectly`

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        }
предлагаю переписать этот метод с учетом всех правок, что я указал выше.

но еще проблема в том, что алгоритм самого теста мне как-то не нравится. ты уверен, что эти тесты будут запускаться именно в таком порядке, в котором ты их расположил в классе? ок, может так и будет, но давай лучше перепишем более универсально, чтобы один тест не зависел от другого. потому что допустим потом кто-то другой захочет дописать еще один тестовый метод в этом классе и может получиться так, что на момент запуска этого теста - в репозитории того юзера из прошлого теста уже не будет.
в лучшем случае - тест завалится и мы это сразу увидим (если там 0 юзеров и мы попытаемся оттуда удалить кого-то)
в случае средней паршивости - наши тесты будут работать не так, как предполагалось. валиться будут одни тесты, хотя причина будет - в других. поверь, тут даже детальный дебаг не спасет (потому что дебажить же ты будешь тот тест, который заваливается, а не тот, который приводит к этому)
ну и худший случай - это если мы реально удалим тут какого-то настоящего юзера из бд.

поэтому алгоритм такой: 

1. сначала явно добавили нового юзера
2. потом явно его удалили
3. удостоверились, что:
- список уменьшился на 1 от того, которым он был после добавления
- объекта юзера нет в списке
- список ровной той длинны, какой он был и в начале теста

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +                    Assertions.assertNotEquals(userBefore, userAfter);
ты здесь сравниваешь не юзеров, а объекты типа Optional. конечно они всегда будут разные :)

надо сначала удостовериться, что в каждом из них есть юзер, а потом уже подоставать из них юзеров и сравнивать юзеров

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +                    Assertions.assertNotEquals(userBefore, userAfter);
трехуровневая вложенность - это плохо.
лучше в этом случае проверяй (не через ифы, а через ассерты) "негативные" сценарии. тогда если код пройдет все проверки негативных сценариев - только тогда он дойдет до твоей основной проверки неравенства юзеров.
серьезно, ты сам увидишь как твой код стал более читабельным без всех этих вложенностей

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        long userId = usersBefore.get(((int) sizeBefore - 1)).getId();
снова же, надеяться, что последний элемент в бд будет именно тот, который нам надо - ненадежно.
лучше снова же сначала добавить тестовую запись, потом ее редактировать.
а удалит за тебя весь этот "мусор" тот метод, который ты пометил аннотацией `@AfterAll`

к тому же, каст к инту лучше было бы вынести на строчку выше. потому что в этой строке слишком много скобочек получается

2020-10-27 22:29 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public static void destroyTestData(@Autowired UserRepository userRepos) {
было бы неплохо в этом методе писать в логи сколько записей в бд было удалено по окончании работы метода

2020-10-28 13:55 UTC, klimenkoMA commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=false
Окей, принял

2020-10-28 16:47 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public static void destroyTestData(@Autowired UserRepository userRepos) {
Поле класса с таким названием уже есть, мне показалось, что userRepository1 смотрится хуже, чем userRepos

2020-10-28 16:50 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        for (int i = 0; i < users.size(); i++) {
Тут я в трех соснах заблудился - я помню, что при работе с итератором нельзя в том же цикле удалить объект из списка. Но удаление на самом деле происходит в БД, а не в списке users. Поэтому, конечно же, нужно использовать  foreach :)

2020-10-28 16:52 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            }
Вот тут ждал разворот :) Валидатор на JavaRash такую ерунду пропускал, но я понимал на тот момент, что в продакшене не может быть таких ходулей :) Просто я не изучал регулярки, и решил побыстрее сделать задание. Теперь выбора не осталось - регулярки :)

2020-10-28 16:54 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            } catch (Exception ignored) {
Спасибо, отличное объяснение, учту

2020-10-28 16:54 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        List<User> userBefore = userRepository.findAll();
Принял, переделаю

2020-10-28 17:02 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        if (!userBefore.contains(user) & user.getName() != null || user.getEmail() != null) {
Побитовое И видимо от неправильного понимания механизма сравнения. Где то вычитал, что после логического И, в случае успеха, остальная часть выражения отбрасывается. Валидатор JR пропускал побитовое И, поэтому я его почти всегда его использую.
По null - решил таким образом не допустить в любом случае попадания в БД нулевых полей. Ты писал про такую проверку - я видимо места лучше не придумал, как перед записью объекта в  БД :)
Но почему то не сделал такую же проверку при update... Л-логика 
За логическое ИЛИ стыдно, грубый ляп

2020-10-28 17:03 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +            }
Принял, переделаю

2020-10-28 17:04 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public void whenCalledSave_thenCorrectWriteNewUser() {
Принял, переделаю

2020-10-28 17:04 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        }
Принял, переделаю

2020-10-28 17:05 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +        }
Хорошо, переделаю

2020-10-28 17:09 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +                    Assertions.assertNotEquals(userBefore, userAfter);
Тут буду подробнее изучать Optional, мне его Идея выдала насильно, когда я попытался вытащить один объект из БД методом findById(). То, что я знаю об Optional на данный момент - что он упрощает код, замещая собой проверки на null. Но я не вчитывался и не разбирался глубже, поэтому для меня новость, что оказывается, из Optional нужно вытаскивать объект. Буду разбираться :)

2020-10-28 17:11 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +                    Assertions.assertNotEquals(userBefore, userAfter);
Принял, переделаю

2020-10-28 17:15 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public static void destroyTestData(@Autowired UserRepository userRepos) {
Хорошо, мне нужно тогда в классе поле, которое нужно итерировать при удалении, и его значение вывести в этом методе через объект LogerFactory

2020-10-29 08:56 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public static void destroyTestData(@Autowired UserRepository userRepos) {
ну и ничего страшного, что существует. твоя локальная переменная в методе перекроет поле класса.
это же как в сеттерах, когда у нас есть `this.name` и просто `name`

2020-10-29 08:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +                    Assertions.assertNotEquals(userBefore, userAfter);
да там вроде не сложно. один метод проверяет наличие, другой метод достает объект

2020-10-29 08:59 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +    public static void destroyTestData(@Autowired UserRepository userRepos) {
эмм, нет. внешняя переменная не нужна.
просто количество "успешных" вызовов для удаления посчитай

2020-10-30 17:42 UTC, spasynkov requested changes
в этот раз правок уже поменьше :) в основном - поудалять лишнее

2020-10-30 17:42 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/entities/User.java
> +@Setter
а зачем эти две аннотации? если аннотация `@Data` создает и геттеры и сеттеры ко всем полям

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	}
а чем отличаются эти два метода?

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +			if (user.getEmail().equals("twoBeerOrNotTwoBeer@drunkard.ru")) {
ок. а если нам понадобится изменить этот тестовый имейл? мне надо будет вспомнить все места в проекте, где используется этот имейл?
или может давай сделаем так, чтоб он хранился в какой-то переменной (константе), а методы бы просто обращались к ней? и тогда достаточно было бы поменять мыло только в одном месте

и давай поменяем на что-то более тривиальное :) типа `test@example.com`

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		String name = String.valueOf(System.currentTimeMillis());
поскольку от идеи с регулярками отказались, и мы добились уникальности тестовым имейлом - давай тогда и имя давать какое-то понятное. например, _test user_
ну и тоже сделать так, чтобы это была общая константа для разных тестовых методов

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		) {
это у тебя идея настроена так, чтобы перенос тут делать? если да - поправь, пожалуйста, чтобы в одну строку была с самим фором

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		) {
и тут тоже

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		LOGGER.debug("**********");
очень информативно (на самом деле нет)

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		LOGGER.debug("**********");
вообще не понимаю что тут происходит и зачем это все.
реально на каждого юзера в базе данных надо выводить список юзеров??

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		LOGGER.debug("**********");
ааа, ты там переменную назвал userList, хотя это ни разу не список, а просто юзер.
нет, названия переменных - это очень важно.

но все-равно, в логах эта информация не нужна. в продакшен базе данных могут быть сотни тысяч юзеров, а то и много миллионов. ты представляешь, что один запуск твоего теста может "сожрать" всю память, отведенную для записи логов, и из-за этого "потрутся" какие-то действительно важные записи

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		}
тут тоже это не надо, я считаю

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingNewUser.contains(user));
перенеси этот ассершен повыше. там, где ты получаешь этот список. получил список - сразу проверил. логично же.

потому что проверка в блоке кода, где происходит сохранение - как-то не оч смотрится

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		//saving new user
не очень информативный коммент. по названию метода это и так понятно :)

лучше бы написал зачем ты тут сохраняешь юзера
```suggestion
		// saving new user to test update on it
```

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertEquals(listSizeBeforeSaving + 1, listSizeBeforeDeleting);
не уверен, что эти ассершены нужны. мы ведь это проверяем в методе выше...

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		LOGGER.debug("**********");
тоже не надо

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		}
и это тоже не надо

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		userId = user.getId();
а зачем айдишник нужен?

2020-10-30 17:42 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		User userForUpdate = new User(userId, nameForUpdate, emailForUpdate);
аа, вижу. ты создал нового юзера...

нет, так ты проверишь, что юзер перезаписывается.
а тебе надо проверить, что юзер обновится. обновится - это когда ты существующему объекту изменил имя, вызвал метод сохранить на _этом же_ юзере - и проверил, что в базе его значение обновилось. так же и с мылом

2020-10-31 05:48 UTC, klimenkoMA commented on src/main/java/com/example/telegrambotinsurance/entities/User.java
> +@Setter
Не знал, уберу :)

2020-10-31 05:49 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	}
Ничем, как я понял, ты попросил сделать удаление мусорных юзеров после каждого метода в классе и потом еще раз пройтись в @AfterAll

2020-10-31 05:49 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +			if (user.getEmail().equals("twoBeerOrNotTwoBeer@drunkard.ru")) {
Принял, поменяю

2020-10-31 05:50 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		) {
Хорошо

2020-10-31 05:51 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertEquals(listSizeBeforeSaving + 1, listSizeBeforeDeleting);
Понял, я думал каждое добавление и удаление в БД нужно проверить, изменился ли размер

2020-10-31 05:51 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		LOGGER.debug("**********");
Принял, уберу

2020-10-31 05:54 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		userId = user.getId();
Я же должен знать, какую строку в БД мне нужно апдейтить. Есть уникальное мыло - но айди же будет надежнее. 
Этот айди я вставляю в юзера, который будет апдейтить существующую запись

2020-10-31 05:55 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		User userForUpdate = new User(userId, nameForUpdate, emailForUpdate);
Все, понял, вытащить юзера из базы, сделать ему setName, setEmail , потом записать в базу обновленные данные

2020-10-31 11:36 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	}
ну да.
но я думал ты сделаешь два метода, пометишь их аннотациями нужными, а внутри каждого из них - вызовешь какой-то третий, в котором и будет находиться весь этот код. в одном месте.
или попробуешь на один и тот же метод поставить обе эти аннотации :)
но точно не дублированием кода :)

2020-10-31 12:43 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	}
теперь понял, сделаю по-другому

2020-10-31 12:58 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		String name = String.valueOf(System.currentTimeMillis());
Хорошо

2020-10-31 13:11 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		LOGGER.debug("**********");
Согласен, не нужно в логах содержимое базы, только во время написания тестов для быстрой самопроверки можно, но потом надо удалять

2020-11-01 00:57 UTC, spasynkov requested changes
пару моментов еще осталось неясных...
да и ветки до сих пор конфликтуют...

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
здесь @Autowired не нужна.
ты же сам этот метод вызываешь, а не спринг за тебя.
вот тестовые методы ты сам нигде не вызываешь. их за тебя вызывает сам спринг, поэтому там ты можешь у него попросить что-то тебе дать туда.

но метод который ты вызываешь явно, сам - спринг к нему дела не имеет. поэтому аннотация лишняя

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	public void deletingTestObjectsAfterMethod(@Autowired UserRepository userRepository) {delete(userRepository);}
а пробовал создать один метод, и на нем обе эти аннотации поставить?

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingNewUser.contains(user));
это решил не делать?

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		//saving new user
и это?

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertEquals(listSizeBeforeSaving + 1, listSizeBeforeDeleting);
это тоже решил оставить?

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingUser.contains(user));
нашел возможный баг тут. у нас ломбок по умолчанию создает метод иквалз по всем полям класса. поэтому пользователи:
```
{id=null, name="Андрей", email="andrey@gmail.com"}
{id=3210, name="Андрей", email="andrey@gmail.com"}
```
будут считаться "разными. соответственно и тут, когда ты делаешь contains - то будет проверка по иквалз, которая вернет фолс и получишь фолс.
хотя логически мы понимаем, что это один и тот же юзер.

поэтому я предлагаю исключить айдишник в классе Юзер из иквалза. и поскольку иквалз мы не сами писали, а нам его ломбок сгенерировал - то почитай в интернете какую аннотацию и куда надо поставить для того, чтобы исключить из иквалз какое-то поле :)

2020-11-01 00:57 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/entities/User.java
> +import java.util.List;
а зачем здесь этот импорт? у тебя ж нигде не используется список никакой

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		String email = "masterOfUniverse@deathstar.empire";
а тут ничего не надо было поменять?

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		String email = "masterOfUniverse@deathstar.empire";
ааа, или это такая задумка? сначала создать юзера, а потом сделать ему апдейт?

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		//checking the absence of a new user in the database and checking the database size change
а отсутствие чего ты тут проверяешь? а то я не вижу что-то такой проверки...

2020-11-01 00:57 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersAfterSavingNewUser.contains(user));
а зачем эта проверка?
опустим она не прошла и тест завалился. нам это о чем-то говорит? я просто не понимаю что ты проверяешь тут :)

2020-11-01 07:37 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
Дело в том, что @AfterAll требует статического метода, @AfterEach - не статического. Объект репозитория у нас не статический. И получается так, чтобы все три метода заработали - нужно в каждый заинжектить объект репозитория через @Autowired. И по этой же причине нельзя использовать одновременно @AfterAll и @AfterEach на одном методе

2020-11-01 07:38 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	public void deletingTestObjectsAfterMethod(@Autowired UserRepository userRepository) {delete(userRepository);}
Да, не получилось, выше написал почему

2020-11-01 07:46 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingUser.contains(user));
Если я тебя правильно понял - я этот момент описывал в телеге. 
![image](https://user-images.githubusercontent.com/71225560/97797513-cd196900-1c2e-11eb-8c93-82a0697ea666.png)
В тот момент, когда произошла запись юзера с нулевым id в БД - id перестает быть нулевым и в БД и в объекте, с которым продолжает работать программа. Поэтому и все ассерты, проверяющие наличие нашего юзера в списке - срабатывают без фейлов. Однако, ты гораздо опытнее меня и знаешь в 100500 раз больше - возможно, в продакшене что-то может поменяться. И тогда лучше обезопасить тестирование исключением поля id из сравнения

2020-11-01 07:56 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
С ветками вообще запутался - дев качается с сервера без изменений в файлах, мне кажется проще удалить два этих файла и скачать их заново

2020-11-01 07:57 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		String email = "masterOfUniverse@deathstar.empire";
Да, мы же все равно перезапишем поля этого юзера под статические , поэтому неважно, какие поля использовать до апдейта

2020-11-01 07:59 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersAfterSavingNewUser.contains(user));
Проверяю, нет ли такого юзера в базе. Если завалится  - значит есть юзер, и это будет значить, что при тесте не почистилась база почему-то, либо чьи-то шуточки :)

2020-11-01 09:05 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersAfterSavingNewUser.contains(user));
ну тогда вот это и надо было добавить в комментарий.
то, что делает метод contains - понятно и так. а вот зачем - лучше уточнить :)

2020-11-01 09:05 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		String email = "masterOfUniverse@deathstar.empire";
ага, ок

2020-11-01 09:18 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingUser.contains(user));
ну тут такой момент, как мы считаем, одинаковые или разные такие объекты? один и тот же юзер, или разные юзеры?
```
{id=null, name="Андрей", email="andrey@gmail.com"}
{id=3210, name="Андрей", email="andrey@gmail.com"}
```

или вот такие
```
{id=1234, name="Андрей", email="andrey@gmail.com"}
{id=3210, name="Андрей", email="andrey@gmail.com"}
```

это разные пользователи или одинаковые в нашем понимании? :)

если в бд есть пользователь `{id=3210, name="Андрей", email="andrey@gmail.com"}`
и я хочу добавить пользователя `{id=null, name="Андрей", email="andrey@gmail.com"}`
я проверяю через `contains()` - получаю `false` (потому что `equals()` вернет `false`)
добавляю юзера
он идет логиниться. в какой из своих профилей он попадет? а при следующем логине? :) неизвестно
а если предположить, что на новом аккаунте он оплатил дорогущую подписку, а на старом нет - вот тебе недовольный клиент, гневные отзывы в интернете и может даже заявки в суд (по вине программиста. потому что программист посчитал, что это разные объекты юзеров)

2020-11-01 09:20 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingUser.contains(user));
то-есть, тут вопрос не в том, что во время записи в бд юзеру присваивается айдишник. это правильно
а в том, что джава считает объект с айдишником и без - разными объектами по своей сути

2020-11-01 09:21 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingUser.contains(user));
Теперь понял, спасибо :) Исправлю

2020-11-01 09:22 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersAfterSavingNewUser.contains(user));
Окей, добавлю :)

2020-11-01 09:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
это понятно. что два разных теста (один статический, второй не статический) требуют объект репозитория. тут никаких вопросов нет.

мой вопрос в том, что зачем эта аннотация в методе, который ты сам, вручную вызываешь? вот именно метод `delete()` в 27й строке тут

2020-11-01 16:42 UTC, klimenkoMA commented on src/main/java/com/example/telegrambotinsurance/entities/User.java
> +import java.util.List;
![image](https://user-images.githubusercontent.com/71225560/97808856-5bffa300-1c7a-11eb-86d1-eb03f0371b45.png)
вот тут используется :)

2020-11-02 21:24 UTC, spasynkov requested changes
в основном осталось то, что я писал раньше, но ты проигнорировал это.
пока мы по этим моментам не придем к общему мнению - код в дев не попадет :)

2020-11-02 21:24 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/entities/User.java
> +import java.util.List;
это хорошо, но я тебе про класс User, а ты мне - про тесты :)

2020-11-02 21:24 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
что-то я смотрю ничего не изменилось по этой правке...

2020-11-02 21:24 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		//saving new user
второй раз отправляешь на ревью этот код без изменений... если не согласен с чем-то - ну так напиши, а не просто игнорируй

2020-11-02 21:24 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertEquals(listSizeBeforeSaving + 1, listSizeBeforeDeleting);
и тут тоже...

2020-11-02 21:24 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersAfterSavingNewUser.contains(user));
тоже, написал что добавишь, но ничего не изменилось... передумал? почему не отписал тогда?

2020-11-03 05:15 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
![image](https://user-images.githubusercontent.com/71225560/97951836-8487ba00-1dac-11eb-88bf-796220f4416c.png)
Не хочет без инжекта работать. Я перепробовал много вариантов, пока не оставил этот

2020-11-03 08:58 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersBeforeSavingNewUser.contains(user));
Прошу прощения, одно из самых глупых занятий человека - игнорить ментора.
У меня две грубых ошибки:
-  переписка в гитхабе открыта в нескольких вкладках, и похоже, что я в них запутался
- я решил, что мне достаточно будет только переписать комменты, без физического перемещения строчек кода
Исправляюсь

2020-11-03 09:22 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		//saving new user
Прошу прощения, исправил

2020-11-03 09:22 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertEquals(listSizeBeforeSaving + 1, listSizeBeforeDeleting);
Виноват, исправил

2020-11-03 09:22 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		//checking the absence of a new user in the database and checking the database size change
Исправил

2020-11-03 09:22 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +		Assertions.assertFalse(listOfUsersAfterSavingNewUser.contains(user));
Не дописал, прочел невнимательно, прошу прощения
Исправил

2020-11-03 22:45 UTC, spasynkov requested changes
верни переменную, но без аннотации
и разберись со счетчиком

2020-11-03 22:45 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static void delete(@Autowired UserRepository userRepository) {
ты шутишь надо мной?)
конечно он не будет так работать. ведь переменная `userRepository` не существует в области видимости этого метода.

я говорил о том, чтобы убрать саму аннотацию `@Autowired`, а не переменную вообще.
конечно без переменной оно не работает)

2020-11-03 22:45 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static int deletingCounts = 0;
я смотрю ты сделал эту переменную статической?
а зачем?
программу запускал, логи смотрел?
![1](https://user-images.githubusercontent.com/14253682/98048676-df65f380-1e36-11eb-8dec-df8cd64f5288.png)
тебя не смущает, что там судя по логам после каждого теста из базы удаляется все больше и больше записей? это что получается, у тебя с каждым тестом все больше и больше говна в бд пишется? или все-таки проблема со счетчиком?

2020-11-04 06:26 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/repositories/UserRepositoryIntegrationTest.java
> +	private static int deletingCounts = 0;
![image](https://user-images.githubusercontent.com/71225560/98076601-9c7c3e00-1e7f-11eb-8a40-1528a833b42a.png)
На этот пост я ориентировался, почему я решил, что нужно количество вызовов метода delete() моего класса посчитать, а не количество реально удаленных записей из БД - я не знаю. 
У меня был реализован правильный вариант подсчета удаленных записей - я его в последнем пуше переписал вот таким образом
Исправлю

2020-11-04 18:58 UTC, spasynkov approved these changes
вроде все ок

2020-11-04 19:03 UTC, merged