Tas#9 create app entry point babin vas
spasynkov/telegram-bot-insurance pull request #17
Opened 2020-11-06 10:40 UTC by babinvas

Close #9

2020-11-07 14:17 UTC, spasynkov requested changes
пока не работает как задумано в задаче :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> + * Класс рест контролеов.
опечатка. да и описание непонятное, честно говоря.


тот класс описывает объект одного-конкретного рест-контроллера, с одной единственной функцией: слушать запросы от апи телеграма

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +public class ClientController {
соответственно и тут, клиент-контроллер? мне лично непонятно его назначение по названию.

а название надо придумать такое, чтобы было понятно что он делает даже не открывая класс :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +	public String getClientPostRequest(@PathVariable("token") String token, JSONObject jsonObject) {
название этого метода мне тоже не нравится :) не совсем понятно что он делает из названия.
получить клиентский пост запрос? слишком как-то абстрактно.
как насчет `recieveAndProcessIncomingMessage()`? не хотелось бы тут использовать гет в названии потому что тогда можно подумать, что это геттер какой-то. гет - это скорее "взять", а "получить" - это ресив. к тому же этот метод не столько получает сообщение (за него это спринг томкат и делают), а скорее обрабатывает входящее сообщение. собственно, process incoming message так и переводится :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +			return "{\"status\":\"ok\"}";
все верно, но давай тут не контроллер будет формировать результат, а сам сервис.
а контроллер будет возвращать то, что вернул сервис.
об этом я написал в последнем пункте задачи: _контроллер (а соответственно, изначально сервис) должен вернуть в ответ {"status":"ok"}_
стараемся в контроллерах не держать логики вообще.
потому что сейчас будет эта строка. потом будет "а давайте в таком случае возвращать эту строку, а в другом случае - другую" - и естественно этот иф попадет сюда же. потом еще куча ифов нарастет тут, и получится, что часть логики у нас будет в сервисе, а часть - в контролере.

а если сразу вся логика будет в сервисе - то и при добавлении новой фичи - мы найдем существующую логику в сервисе и сразу там и допишем новое что-то)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +		}
но блок обработки исключения - оставляем тут, да. потому что если в сервисе что-то забудем отловить - то оно отловится тут наверняка :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +			String error = "ОК";
зачем эта переменная? :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/AbstractBot.java
> +    public void processMessage(Message message) {
прикольно, но нет :)

представь, что ты создаешь нового бота-наследника. и случайно забыл переопределить ему этот метод. что будет? бот не будет работать. это в лучшем случае. в худшем - он будет работать по той логике, которую потом кто-то напишет тут...

надо сделать так, чтобы при создании наследника - мы **обязаны** были бы переопределить этот метод

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
ты же видел сообщение, которое присылает телеграм нам. там джейсон такой огромный.
почему бы не добавить сюда хотя бы переменную для текста сообщения?

а еще лучше - текст сообщения, дата, от кого (юзернейм хотя бы), ну и айдишник чатика, куда отправлять ответ.
в идеале - создать структуру классов, которая бы полностью соответствовала бы входящему сообщению от телеграмма, но это я думаю потом сделать, отдельная задача под это будет.
для начала надо хотя бы получать текст сообщения и куда слать ответ :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/BotServiceImpl.java
> +            String error = "Unable to find bot with token" + "'<" + token + ">'";
угловые скобочки тут не нужны :) то я когда тебе писал так выделил, чтобы было понятно, что это не слово токен, а сам токен бота

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +public interface ClientService {
клиент сервис - вообще непонятно что такое :)
подумай еще раз чем занимается этот интерфейс (точнее, объекты такого типа) и придумай ему более подходящее название :)
ну и классу-реализации тоже, конечно :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +import org.springframework.boot.configurationprocessor.json.JSONObject;
это точно тот класс, объекты которого нам нужны? пробовал доставать из него какие-то значения?

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +	// Метод получает бота оп токену, преобразует  JSONObject в объект Message
опечатка "оп"

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +	void createMessage(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
этот метод у тебя не просто создает сообщение... подумай как его переименовать

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +	// Метод получает бота оп токену, преобразует  JSONObject в объект Message
тоже опечатка "оп"

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +	// и предаёт этот объект бот через метод processMessage
`bot.processMessage(message)` - это не передавать объект бот через метод
ты же наоборот, у объекта бота вызываешь метод и передаешь туда сообщение.
по сути ты тут говоришь боту, которого ты нашел: "эй, бот, тут вот тебе сообщение пришло, держи, обработай его"

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		// олучаем бот по токену.
опечатка

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		String jsonString = jsonObject.toString();
так а зачем ты тогда джейсон передавал, и у спринга джейсон просил в контроллере, если здесьты его назад к строке приводишь?) получается, изначально спринг получил строку из запроса, но видит, что ты просишь у него джейсон. он прилагает усилия чтобы распарсить эту строку в джейсон и дать тебе, а ты этот джейсон снова к строке приводишь)
просил бы тогда уже стрингу у спринга :)

2020-11-07 14:17 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		Message message = objectMapper.readValue(jsonString, Message.class);
не понимаю зачем эта строка, если ты ничего не достаешь из джейсона, и получаешь тут пустой объект.
то-есть, боту приходит строка "_привет_" - ты получаешь пустой объект
боту приходит строка "_я не пустой объект!!!_" - ты снова получаешь тут пустой объект.
в чем тогда смысл этой строки? :)

тут надо получать объект сообщения. с текстом, отправителем, итд... я это все расписал в комментарии к классу `Message`

2020-11-07 14:33 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> + * Класс рест контролеов.
Думал, чтоб все запросы и гет тоже туда кинуть, чтоб не плодить контролеры.

2020-11-07 14:42 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> + * Класс рест контролеов.
Пр поводу:

_"тот класс описывает объект одного-конкретного рест-контроллера, с одной единственной функцией: слушать запросы от апи телеграма"_

Думал, чтоб все запросы к клиенту были в этом контролере и пост, и  гет, и пут, и делет.
Чтоб не плодить кучу контролеров.

Будем делать отдельные контролеры?

2020-11-07 15:33 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> + * Класс рест контролеов.
Опечатки исправил.

2020-11-07 16:01 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +	public String getClientPostRequest(@PathVariable("token") String token, JSONObject jsonObject) {
А может так **receiveAndProcessIncomingPostRequest**?

2020-11-07 16:04 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +			String error = "ОК";
Забыл, когда пробовал разные варианты удалить.

2020-11-07 16:07 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/AbstractBot.java
> +    public void processMessage(Message message) {
Тогда надо класс сделать абстрактным.
Я думал об это сразу, но не хотел менять логику.

_AbstractBot_ делаем **абстрактным**?

2020-11-07 16:11 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
`{
    "update_id": 641170930,
    "message": {
        "message_id": 785,
        "from": {
            "id": 652216725,
            "is_bot": false,
            "first_name": "Stas",
            "last_name": "Pasynkov",
            "username": "spasynkov",
            "language_code": "uk"
        },
        "chat": {
            "id": -485469147,
            "title":"\u0420\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u043a\u0430 \u0442\u0435\u043b\u0435\u0433\u0440\u0430\u043c-\u0431\u043e\u0442\u0430",
            "type": "group",
            "all_members_are_administrators":false
        },
        "date": 1586690677,
        "text": "\u0440\u0430\u0441\u0448\u0430\u0442\u0430\u043b\u0438\u0441\u044c \u043a \u0447\u0435\u0440\u0442\u0443 \u043d\u0435\u0440\u0432\u044b"
    }
}`

2020-11-07 16:23 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
Выше комент для себя из телеграм твой.

2020-11-07 16:32 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +public interface ClientService {
Та же логика.
Чтоб не плодить кучу сервисов.
Все запросы их контроллера Client обрабатываются в этом сервисе.

Если будем делать для каждого запроса свои контроллеры и сервисы, то переделаю, конечно.

То же вопрос, будем делать для каждого запроса (пост, гет и т.п.) свои контролеры и сервисы?

2020-11-07 16:37 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +import org.springframework.boot.configurationprocessor.json.JSONObject;
Ты про это
_import org.springframework.boot.configurationprocessor.json.JSONObject_?

Это Идея сама подсказал и создала )):
_import com.fasterxml.jackson.core.JsonProcessingException_

Но это наше исключение:
_import com.example.telegrambotinsurance.exception.BotNotFoundException_

Поясни о чём речь именно?

2020-11-07 16:45 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +	// Метод получает бота оп токену, преобразует  JSONObject в объект Message
Исправил.

2020-11-07 16:50 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +	void createMessage(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
А так:
**processReceivedObjectIntoMessageObject**?

2020-11-07 16:51 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +	// Метод получает бота оп токену, преобразует  JSONObject в объект Message
Да, как там выше написал.
Тут тоже сразу поправил.

Я и так всё в ворде проверяю.
Заведу за привычку.

2020-11-07 16:52 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		// олучаем бот по токену.
Да уж. (((

2020-11-07 16:56 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		String jsonString = jsonObject.toString();
Как я понял РестКонтроллер получает объект дейсон.
**Разве нет?**

А **objectMapper.readValue()** работает со строкой, не джейсон, пришлось распарсить.

2020-11-07 17:00 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		Message message = objectMapper.readValue(jsonString, Message.class);
Я думал, мы вроде обсуждали, что пока класс пустой будет и потом мы его заполним так как он сложный.
Поэтому, этот метод, который (по идее) будет преобразовывать в наш в будущем правильный класс.

_Когда я добавлю в класс Message поля этот вопрос снимается?_

2020-11-07 17:03 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
По факту **"message"** - это массив, как и **"from"** и **"chat"**?
Или это **другие объекты**?

2020-11-07 20:40 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +	public String getClientPostRequest(@PathVariable("token") String token, JSONObject jsonObject) {
можно и так :)
просто мне кажется, что "обработка входящего сообщения" дает чуть больше понимания, чем "обработка входящего пост-запроса". в первом случае, мы явно даем понять, что тут на конкретно будет сообщение от телеги приходить :) а не какой-то абстрактный пост-запрос непойми с чем :)

2020-11-07 20:42 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/AbstractBot.java
> +    public void processMessage(Message message) {
да. я что-то пропустил это на ревью( думал что абстрактный бот будет абстрактным классом сразу, по умолчанию :)
так что да, поправь его, пожалуйста. и метод тоже тут сделай абстрактным

2020-11-07 20:46 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
не
по факту, message - это объект с такими полями (судя по джейсону)
```
int/long messageId;
Sender sender;
Chat chat;
Date date;
String text;
```
в свою очередь, объекты типа Sender и Chat будут иметь свои поля, которые соответствуют джейсону, итд...

просто это тоже не полный джейсон со всеми возможными данными... поэтому надо будет уточнять в документации что еще там может быть, поэтому и говорю, что это будет потом уже, в отдельной задаче.
сейчас нам главное получить текст сообщения и айдишник чата для ответа

2020-11-07 20:47 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
ааа, ну а внутри библиотеки той джейсона - там да, там эти данные могут в нераспаршеном виде быть представленны как мапа... но в итоге нам надо будет получить **наш** объект

2020-11-07 20:48 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +public interface ClientService {
я не понял вопроса...(

2020-11-07 20:48 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +import org.springframework.boot.configurationprocessor.json.JSONObject;
да, про `org.springframework.boot.configurationprocessor.json.JSONObject`

2020-11-07 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +	void createMessage(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
но ведь у тебя в реализации он не просто получил строку и распарсил ее в наш объект Message
он же еще потом очень важную вещь делает :) которая даже важнее, чем просто распарсить сообщение

2020-11-07 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		String jsonString = jsonObject.toString();
ну я могу и ошибаться, но кажется что ты у спринга попросишь получить - то он тебе и даст.
если у спринга получится распарсить строку в джейсон - он так и сделает...
но если тебе изначально нужна была строка - то можно было сразу ее попросить :) попробуй сразу строку получать в контроллере и сюда, в этот метод эту же строку и передавать

2020-11-07 20:57 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		Message message = objectMapper.readValue(jsonString, Message.class);
нуу, он не снимется, а изменится :)
потому что мы сейчас не готовы создать класс Message полностью с теми полями, которые будут приходить от телеги.
тот пример входящего сообщения - это самый простой пример.
ведь еще могут скинуть не текст, а фотку. или геолокацию, или пересланное сообщение из другого чата, или контакты чьи-то... да и просто событие добавления бота в беседку какую-то - это тоже срабатывает ивент как будто боту отправили сообщение...
мы сейчас не готовы сделать наш объект Message таким, чтобы он учитывал все возможные варианты.
сейчас нам надо чтобы мы могли достать текст и и куда отправлять ответ.

проблема в этом маппере, как я понимаю, в том, что пока ты ему не дашь "правильный" класс со всеми нужными полями - он тебе не будет нормально собирать нужный нам объект.

но ты попробуй, конечно :)

просто сейчас даже не на чем пробовать, потому что класс пустой :)

2020-11-07 20:58 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		Message message = objectMapper.readValue(jsonString, Message.class);
в общем, если в двух словах, то сейчас делаем быстро и по-простому, чтобы просто работало.
а потом уже будет отдельная задача на то, чтобы довести до ума

2020-11-08 11:55 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +	public String getClientPostRequest(@PathVariable("token") String token, JSONObject jsonObject) {
Хорошо сделал.
**receiveAndProcessIncomingMessage**

Но может получиться путаница так как у нас есть класс Message.

2020-11-08 11:59 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +			String error = "ОК";
Удалил.

2020-11-08 12:06 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/BotServiceImpl.java
> +            String error = "Unable to find bot with token" + "'<" + token + ">'";
Откорректировал.

2020-11-08 12:20 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +	// Метод получает бота оп токену, преобразует  JSONObject в объект Message
Исправил.

2020-11-08 12:23 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +	// и предаёт этот объект бот через метод processMessage
Опечатка:
_в объект Message и предаёт этот объект **бот**_

Надо было:
в объект Message и предаёт этот объект бот**_у_**

Лучше наверное:
Метод получает определённого бота по токену, преобразует JSONObject в объект Message и предаёт этот объект Message полученному боту через метод processMessage

2020-11-08 12:25 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		// олучаем бот по токену.
Исправил.

2020-11-09 14:35 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/AbstractBot.java
> +    public void processMessage(Message message) {
Сделал.

2020-11-09 15:27 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> + * Класс рест контролеов.
Переименовал.

2020-11-09 15:27 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +public class ClientController {
Переименовал.

2020-11-09 15:29 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +public interface ClientService {
Переименовал.

2020-11-09 15:32 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +	void createMessage(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
Переименовал.

2020-11-11 17:17 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/ClientController.java
> +			return "{\"status\":\"ok\"}";
Перенёс.

2020-11-11 17:20 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +
Создал три поля в Message классе.
Реализовал получения параметров из JSON и создание объекта Message с этими параметрами.

2020-11-11 17:22 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		String jsonString = jsonObject.toString();
Реализовал получение JSON.
Убрал лишний парсинг.

2020-11-11 17:23 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientService.java
> +import org.springframework.boot.configurationprocessor.json.JSONObject;
Реализовал с net.minidev.json.JSONObject.
Эта библиотека ловит JSONObject в РестКонтроллере.

2020-11-11 17:25 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/ClientServiceImpl.java
> +		Message message = objectMapper.readValue(jsonString, Message.class);
Реализовал.

2020-11-12 11:23 UTC, spasynkov requested changes
код не работает.
это можно было бы узнать и при помощи тестов, а не на ревью...
но тестов тоже нет

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +}
ты ж в курсе, что у нас на проекте используется lombok? :)
и вот этого всего можно было не писать, а проставить две аннотации просто.
давай придерживаться одного стиля, и если уже в одних классах используется ломбок - то использовать его и в других

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/BotServiceImpl.java
> +            String error = "Unable to find bot with token: " + "'" + token + "'";
а зачем тут первый плюс?

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> + * Класс обработки все запросов от клиента с телеграм (POST, GET, PUT, DELETE).
опечатка во "все"
к тому же, если я не ошибаюсь, то телеграм нам отправляет только post-запрос с новым сообщением. никаких гет/пут/делете он нам не шлет
кроме того, это все принимает контроллер, запросы эти все... у сервиса же - совсем другая задача

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +	String convertDataToMessageObjectAndSendItToBot(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
а почему бы не просто `recieveAndProcessMessage`? или как-то так

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +public interface WebhookMessageHandlerService {
а зачем здесь слово _message_?

2020-11-12 11:23 UTC, spasynkov commented on pom.xml
> +		</dependency>
а зачем эта зависимость, если ты сделал без использования этой библиотеки? :)

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerServiceImpl.java
> +		Message message = new Message(message_id, date, text);
этот код не работает.
всегда проверяй свой код перед тем, как просить кого-то его смотреть. зачем смотреть то, что даже не работает? задача ведь не сделана

я тебе давал пример джейсона, который будет приходить от телеграма.
я запустил сервак на твоей ветке и отправил запрос с джейсоном тем.
в итоге выпал NPE, понятное дело объект сообщения не был создан и бот это сообщение не запроцессил

2020-11-12 11:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookMessageHandlerController.java
> +			return "{\"error\":\"" + e.getMessage() +"\"}";
и вот здесь поправь немного...
не у всех исключений есть есть message
давай так, если месадж нул или пустой - то выводить тут название самого исключения
например, этот НПЕ, что у тебя вылетает - не показывается тут и в итоге в ответе имеем `{error:null}` что не очень информативно)

2020-11-12 11:52 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/BotServiceImpl.java
> +            String error = "Unable to find bot with token: " + "'" + token + "'";
Не понял, что ты имеешь ввиду?

2020-11-12 11:54 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> + * Класс обработки все запросов от клиента с телеграм (POST, GET, PUT, DELETE).
Забыл изменить, это запрос делал ещё до того, как выяснил, что будет только POST и конкретика по каждому запросу.
Изменю конечно.

2020-11-12 12:04 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +	String convertDataToMessageObjectAndSendItToBot(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
Ну мы вроде говорили, да и везде написано, что метод должен описывать свою работу.
Плюс, у нас в контроллере **WebhookMessageHandlerController** уже есть наподобие метод **receiveAndProcessIncomingMessage** не будет ли путаницы?

Может тогда конкретизировать:
- WebhookMessageHandlerControlle -> receiveAndProcessIncomingMessageOfController
- WebhookMessageHandlerService -> recieveAndProcessMessageOfService
?

2020-11-12 12:07 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +public interface WebhookMessageHandlerService {
Потому, что моя логика была такой - **Сервис обработки вебхук сообщения**.
_Убрать?_

2020-11-12 12:08 UTC, babinvas commented on pom.xml
> +		</dependency>
Думал вдруг будем использовать.
Уберу конечно.

2020-11-12 12:10 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerServiceImpl.java
> +		Message message = new Message(message_id, date, text);
Странно очень.
Я тестил через постман работал, правда с моим запросомом.
Надо попробовать с телеграм, там есть отличия?

2020-11-12 12:15 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +}
> ты ж в курсе, что у нас на проекте используется lombok? :)
Если честно не знал, да и не изучал даже lombok.
Буду изучать.

На постмане проверял код работает.
Про тесты думал, но не знал надо ли делать или нет.
Получается ко всему надо по любому.

2020-11-12 12:15 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookMessageHandlerController.java
> +			return "{\"error\":\"" + e.getMessage() +"\"}";
Понял, сделаю.

2020-11-12 14:10 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/BotServiceImpl.java
> +            String error = "Unable to find bot with token: " + "'" + token + "'";
Всё понял.
Исправил.

2020-11-12 17:07 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookMessageHandlerController.java
> +			return "{\"error\":\"" + e.getMessage() +"\"}";
Сделано.

2020-11-12 17:55 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +}
как это не знал?
а ты что, другие классы не смотришь?
у нас общий проект. поэтому каждый должен знать все. иначе если каждый будет знать только свою часть - то и толку от этого не будет, потому что не будет целостной картины

ломбок нечего изучать. там про пару аннотаций основных просто прочитать и все, 15 минут времени.
https://projectlombok.org/features/all
https://habr.com/ru/post/345520/
https://habr.com/ru/post/438870/

я тоже постманом отправил запрос - получил NullPointerException. это не то поведение, которое я ожидал

тесты по желанию, но очень желательно чтобы они были, хотя бы минимальный функционал чтобы проверяли

2020-11-12 17:56 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +	String convertDataToMessageObjectAndSendItToBot(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
надо придумать такие названия, чтобы они были точные, лакончиные, и по возможности короткие :)

2020-11-12 17:57 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +public interface WebhookMessageHandlerService {
а что такое вебхук-сообщение?
сервис обработки вебхуков - это я понимаю
при чем тут сообщения - не понимаю :)

2020-11-12 17:59 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerServiceImpl.java
> +		Message message = new Message(message_id, date, text);
ну конечно на том, что нам будет телеграм присылать :) я ж тебе кидал пример

смысл придумать свою структуру сообщения, написать под свою структуру код - а потом удивляться почему он не работает с сообщениями от телеграма :)

2020-11-12 18:06 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +	String convertDataToMessageObjectAndSendItToBot(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
просто convertDataToMessageObjectAndSendItToBot
конвертироватьДанныеВОбъектСообщенияИОтправитьЕгоБоту - это слишком. в названии метода не надо указывать что он делает чуть ли не построчно. надо придумать такое название, которое бы говорило что этот метод делает вообще, в чем его суть, а не как эта суть реализована в коде. поэтому я и предложил название попроще

если считаешь, что названия recieveAndProcessMessage могут внести путанницу - значит названия классов сделать такими, чтобы было понятно в контексте чего эти названия...

в общем, надо просто сесть, подумать что будет делать этот метод, и постараться в двух словах это описать :)

варианты типа sendPostRequest - тоже не очень информативны, сразу говорю)) сам недавно столкнулся со своими такими методами, где по названию совершенно непонятно было что они делают. да, отправляют пост-запрос - это понятно, но а зачем, для чего они его отправляют, в чем суть этого действия? и да, я тоже сидел переименовывал свои методы, потому что понимал, что это не дело))

2020-11-12 18:08 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +}
если сейчас тесты не готов писать - сделай потом. тогда сейчас заведи карточку (создай новое issue) и опиши там задачу, и сразу можешь себя назначить, но так и оставь ее в туду

2020-11-13 09:44 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +}
Конечно я смотрю, в моей ветке просто его не применяли ещё.
А когда на гигхаб смотрел но думал, что это аннатации jpa.
Я чуть их знаю, но решил потом их изучить более подробно.

2020-11-13 19:07 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +}
Релаизовал.

2020-11-13 19:10 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerServiceImpl.java
> +		Message message = new Message(message_id, date, text);
Реализовал.

2020-11-13 19:12 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +public interface WebhookMessageHandlerService {
**Тесты сделаю другой задачей**, чтобы не задерживать эту задачу.

2020-11-13 20:12 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +	String convertDataToMessageObjectAndSendItToBot(String token, JSONObject jsonObject) throws BotNotFoundException, JsonProcessingException;
Переименовал.

2020-11-13 20:12 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookMessageHandlerService.java
> +public interface WebhookMessageHandlerService {
Сделал.

2020-11-14 20:50 UTC, spasynkov requested changes
код уже работает, но пока неправильно :)
к тому же, заменить комментарии над методами - на джавадоки, и разобраться с исключениями. Может даже завести отдельное исключение типа `IncomingMessageValidationException`, чтоб было прям ващще по-красоте :)

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	// Метод слушает POST запросы по токену определённого бота, обрабатывает полученные сообщения и предаёт их сервису.
скорее просто слушает и передает сервису на обработку... но ладно, это не столь важно

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	// @return status или error.
кстати, мог бы это в виде джавадоков сделать, а не просто комментариев :)
ставишь курсор на метод, жмешь Alt+Enter и выбираешь Add Javadocs

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	public String receiveAndProcessMessage(@PathVariable("token") String token, @RequestBody JSONObject jsonObject) {
`jsonObject` не самое удачное имя переменной тут. там и по типу понятно, что это джейсон-объект. непонятно что будет в этой переменной
лучше что-то типа `content` или `requestBody`

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +@Service
эта аннотация здесь не нужна. спринг не сможет создать объект интерфейса

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	// @return status.
тут тоже переделай на джавадок

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	String receiveAndProcessMessage(String token, JSONObject jsonObject) throws Exception;
ну и здесь `jsonObject` тоже переименовать на что-то более понятное

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	// @return status.
и тут джавадок)

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			throw new Exception("Преданный jsonObject объект в метод convertDataToMessageObjectAndSendItToBot класса WebhookHandlerServiceImpl равен null.");
1. а почему аж целый Exception? почему не RuntimeException например?
чем уже тип исключения, которое ты кидаешь - тем лучше. потому что его потом можно будет более точно отлавливать кетчами.
2. к тому же, проверяемые исключения обычно кидаются кода ты можешь что-то тут еще изменить, исправить програмно.
если же тебе пришел пустой джейсон - то я не думаю, что тут можно что-то програмно исправить и подать сюда непустой джейсон)
3. все такие вещи пишем на инглише) это сообщение будет писаться в логи, так что лучше пусть оно будет более универсальное, чтоб не только мы его могли прочитать, но и саппорт сервиса, на котором будет крутиться наш сервер (он же не всегда локально у нас будет запускаться)
4. текст исключения слишком длинный и детальный. по стектрейсу и так будет понятно в каком оно методе вывалилось, там еще и строка будет указана. текст сообщения нужен для того, чтобы быстро понять что пошло не так. например `Content can't be null`
5. следи за комментариями к коду. очень часто код меняется, а комментарии поправить забывают. после чего долго сидишь и думаешь что это за метод такой `convertDataToMessageObjectAndSendItToBot` и из какого он класса, и при чем он здесь вообще? если что-то переименовываешь - лучше используй Shift+F6 в идее. она тогда найдет по всему проекту все места, где есть еще такая же строка и предложит их переименовать тоже

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			throw new Exception("Предан пустой jsonObject объект в метод convertDataToMessageObjectAndSendItToBot класса WebhookHandlerServiceImpl.");
все то же, что описал по исключению выше

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		if (jsonObject.has("message")) {
хорошо. а что произойдет если в джейсоне, который нам пришел - не будет объекта message?
мы не заходим в этот иф и возвращаем статус ок?

может лучше кинуть исключение?
только сначала проверить что если меседжа не - то кинуть исключение.
а потом уже без елса просто продолжить твой код. это уберет один уровень вложенности

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			JSONObject messageJsonObject = jsonObject.getJSONObject("message");
тут я думаю достаточно просто `messageJson` для понимания

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			if (!messageJsonObject.isEmpty()) {
ну а тут наоборот, чтобы избежать лишнего уровня вложенности сначала проверяем что месадж пустой, и если да - то снова кидаем исключение, и тогда можем дальнейший код писать не в елсе, а просто так.

к тому же, еще бывает так, что приходит такое:
`{"message":null}`
можешь еще учесть и такой вариант :)

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setMessage_id(message_id);
прикольно, конечно, что ты вместо айдишника чата достаешь айдишник самого сообщения...
вот только вопрос: а как наш бот узнает в какой чат ему отправлять ответ?

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				if (messageJsonObject.has("text") && !messageJsonObject.isNull("text")) {
и снова вопрос: а если сообщение без текста пришло? например картинка?
или это уже проблема бота как он будет работать с текстом null? :)

если будешь тут кидать исключение - перенеси создание и наполнение объекта месаджа ниже. то-есть, сначала мы достаем и валидируем все данные
и только после этого создаем и наполняем объект Message

2020-11-14 20:50 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setDate(date);
с датой тоже не все окей.
я ж тебя просил, запускай, проверяй, перед тем, как сдавать задачу.
сдавать неработающий код - это плохая практика (ну или неправильно работающий)
![image](https://user-images.githubusercontent.com/14253682/99156642-2cfe1e00-26cb-11eb-98d3-1a0b068f5d80.png)
в 70м году не было ни телеграма (как интернет-сервиса), ни меня :) поэтому я не мог отправить такое сообщение чисто физически :)

2020-11-16 07:39 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setDate(date);
> сдавать неработающий код - это плохая практика (ну или неправильно работающий)

Конечно, ты прав.
Но, суть, то в том, что я то думаю, что всё хорошо.
Если бы я думал, что код не работает я даже ревью не делал.

Да, и прикол в том, что чем больше я хочу его сделать лучше, тем больше получается ошибок. )

2020-11-16 07:48 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +@Service
Да.
Убрал.

2020-11-16 13:12 UTC, MrErgos requested changes
Надо перенести версию

2020-11-16 13:12 UTC, MrErgos commented on pom.xml
> +			<version>20200518</version>
Надо перенести версии в раздел properties в этом файле
Вот примерно как это делать https://stackoverflow.com/a/37358341/7469463

2020-11-16 14:09 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	// Метод слушает POST запросы по токену определённого бота, обрабатывает полученные сообщения и предаёт их сервису.
Думал завести отдельно да, что-то побоялся.

2020-11-16 14:25 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	// @return status.
Да, точно.

2020-11-16 14:41 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			throw new Exception("Преданный jsonObject объект в метод convertDataToMessageObjectAndSendItToBot класса WebhookHandlerServiceImpl равен null.");
>     1. а почему аж целый Exception? почему не RuntimeException например?
>        чем уже тип исключения, которое ты кидаешь - тем лучше. потому что его потом можно будет более точно отлавливать кетчами.

Думал, не побоялся.

>     2\. к тому же, проверяемые исключения обычно кидаются кода ты можешь что-то тут еще изменить, исправить програмно.
>         если же тебе пришел пустой джейсон - то я не думаю, что тут можно что-то програмно исправить и подать сюда непустой джейсон)

Тогда, просто вернуть сообщение, что Джейсон нул, или лучше свой Иксепшь?

2020-11-16 14:55 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setMessage_id(message_id);
Но, ведь он находится в другой ссылочной переменной, по идее, в chat.
Или мне все создать переменные даже ссылочные и пустые классы, или классы с этими переменными?

Я вытащил те переменные которые которые которые прям находятся к классе мессадж.
А те которые надо создавать отдельные классы нет (ты говорил это отдельная задача).

Может мне всё таки создать всю структуре из классов этого сообщения, что ты дал (from и chat)?

2020-11-16 15:20 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setDate(date);
Самое обидное, что я видел эту дату, думал может такой пример.
Понял, у нас Date милисекунды, а в там Unix time -  в секундах.

2020-11-16 15:28 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				if (messageJsonObject.has("text") && !messageJsonObject.isNull("text")) {
Исправил.

2020-11-16 15:29 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				if (messageJsonObject.has("text") && !messageJsonObject.isNull("text")) {
И вопрос в итоге.

Что делать если я думаю, что всё хорошо и хочу чтоб посмотрели код, а в итоге получается, что он не рабочий и это плохая практика, что в итоге делать?

2020-11-16 15:30 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setDate(date);
Исправил.


**И вопрос в итоге.**

Что делать если я думаю, что всё хорошо и хочу чтоб посмотрели код, а в итоге получается, что он не рабочий и это плохая практика, что в итоге делать?

2020-11-16 18:03 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	// Метод слушает POST запросы по токену определённого бота, обрабатывает полученные сообщения и предаёт их сервису.
Сделал.

2020-11-16 18:04 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	// @return status или error.
Сделал вроде верно.

2020-11-16 18:05 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	public String receiveAndProcessMessage(@PathVariable("token") String token, @RequestBody JSONObject jsonObject) {
Переименовал в requestBody.

2020-11-16 18:33 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setMessage_id(message_id);
зачем тебе создавать всю структуру?
посмотри на свой код. как ты получил `messageJsonObject`? разве тебе пришлось создавать класс Message со всей структурой? нет. ты просто достал джейсон-объект `message` и все. потом достал из него нужные тебе данные.
сделай то же самое с чатом.

для понимая что именно надо будет учесть - посмотри на структуру объекта Message в документации
https://core.telegram.org/bots/api#message
там не на один день работы.
успеем еще этим заняться.
сделай пока просто, по-быстрому

2020-11-16 18:43 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setDate(date);
_что чем больше я хочу его сделать лучше, тем больше получается ошибок_
не совсем так. чем больше кода - тем больше мест и возможностей для ошибок.
чем меньше кода, и чем он проще - тем сложнее наделать ошибок. поэтому это то, к чему и стремимся :) чтобы код был короткий и понятный

да и вообще можешь привыкнуть, что если работаешь с датой, и видишь 70й год - это в 99.9% случаев ошибка :)

чтобы не было так, что думаешь, что все работает как надо, а оказывается, что работает не так - тут достаточно просто спросить. недовыяснил требования значит. просто спросил бы: _а это нормально, что в примере сообщения дата указана за 70й год?_ я бы сразу сказал, что нет :)

пока программист junior - это нормально, что он будет постоянно что-то спрашивать. конечно, вопросы должны быть не "как работает цикл" (должен знать) или "что делает этот метод из библиотеки" (легко гуглится, или смотрится в самом методе по его коду). молчаливый джун - это вреднее для проекта, чем чрезмерно спрашивающий) у меня товарищу часто отказы прилетали с собеседований именно из-за его природной молчаливости.

2020-11-16 18:48 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			throw new Exception("Преданный jsonObject объект в метод convertDataToMessageObjectAndSendItToBot класса WebhookHandlerServiceImpl равен null.");
лучше свое исключение

2020-11-17 12:04 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +				message.setDate(date);
**Нее, я не молчаливый совсем.**
Просто задалбливать не люблю, у тебя ведь основной работы думаю и так хватает, тут ещё и мы.
Тем более, что ты в принципе с нами возишься.

2020-11-17 16:04 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	// @return status.
Сделал.

2020-11-17 16:07 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	String receiveAndProcessMessage(String token, JSONObject jsonObject) throws Exception;
Хорошо.

2020-11-17 16:07 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	// @return status.
Понял.

2020-11-18 14:08 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			JSONObject messageJsonObject = jsonObject.getJSONObject("message");
Поменял.

2020-11-18 14:08 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			if (!messageJsonObject.isEmpty()) {
Сделал.

2020-11-20 00:51 UTC, spasynkov requested changes
в основном не понравилось как назвал переменные. код рабочий.
но надо еще смержить дев в эту ветку, а то без этого гитхаб не даст смержить твой код в дев (там уже много нового с момента, как ты ответвлился из дева под эту ветку)

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> + * Класс обработки сообщений пришедших на вебхук определённого бота.
вебхук - это такой способ взаимодействия. на способ невозможно отправить сообщение

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	 * Слушает запросы вебхука бота и предаёт полученные сообщения и токен сервису.
аналогично и тут, некорректное описание, может ввести в заблуждение

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	 * @param token       Строка с токиеном.
ток~~и~~ен

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +			exceptionAnswer = exceptionAnswer.replaceAll("\\[\"", " '");
я ж говорил. заменить одни символы на другие - это плохой вариант, самый крайний, если ничего другого не получится.
я предложил поискать в интернете как заэкранировать символы для джейсон-строки
ты пробовал `StringEscapeUtils.escapeJson()` из библиотеки Apache Commons

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/exception/IncomingMessageCheckException.java
> +public class IncomingMessageCheckException extends RuntimeException {
2 момента.
во-первых, check - это именно проверка. в данном случае все же чаще используется именно слово валидация, поэтому лучше заменить на validation
во-вторых, почему только Incoming? с другими сообщениями нельзя будет использовать это исключение? ну если мы будем не только входящие сииобщения валидировать, но и исходящие

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +	private int chatId;
ты уверен, что тут хватит инта? почему не байт тогда?
я вот посмотрел в [документации](https://core.telegram.org/bots/api#chat) - и не уверен

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	 * @param token          Строка с токиеном.
тоже ток~~и~~ен

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	 * @param receivedObject JSON объек.
объек

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	 * @param token          Строка с токиеном.
и тут

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	 * @param receivedObject JSON объек.
и тут

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		checkObject(receivedObject);
лучше validate и уже точно без object (тут понятно, что это не примитив)

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		JSONObject messageObject = receivedObject.getJSONObject("message");
по-моему, тут `messageBlock` смотрелось бы значительно лучше.
просто слово object - оно же ни о чем не говорит, по сути. то, что это не примитив - это и так понятно.

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	 * @param receivedObject JSON объек.
снова объек

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			throw new IncomingMessageCheckException("The incoming object cannot be null.");
входящий объект? это снова же очень абстрактно и ни о чем не говорит.
вот читаешь ты логи, а там написано, что АЛЯРМА! какой-то там входящий объект - нулл!
и ты понимаешь, что тебе сейчас предстоит сидеть и ковыряться в коде, но основная проблема в том, что ты понятия не имеешь что это за "входящий объект" и почему это он вдруг сегодня нулл, а вчера таким не был

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject) {
receivedObject тоже можно спокойно заменить просто на json - и все будет значительно понятнее.
этот метод - делает только свою работу. он не должен знать, входящий это объект, или исходящий, или транзитный, или еще какой.
ты ж не будешь делать такой же метод, но с разницей в названии переменной для валидации исходящего объекта? или использовать этот метод, который принимает "входящий объект", а на самом деле подсовывать ему "исходящий"?
нет. этот метод ничего не должен знать о контексте происходящего. ему дали какой-то джейсон-объект - он его проверил, все.

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject, String objectName) {
аналогично, как и выше, но тут еще вторая переменная непонятная. объект имени? имя объекта?
мне кажется тут логичнее смотрелась бы пара: json, key.
получили джейсон и ключ. проверили, что значение не нулл. все логично вроде

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isEmpty(JSONObject receivedObject, String objectName) {
аналогично

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void hasObject(JSONObject receivedObject, String objectName) {
и тут

2020-11-20 00:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +			exceptionAnswer = exceptionAnswer.replaceAll("\\[\"", " '");
кстати, я тут позапускал... квадратные скобки ни на что не влияют. проблема была только в двойных кавычках

2020-11-20 08:54 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +			exceptionAnswer = exceptionAnswer.replaceAll("\\[\"", " '");
> 
> 
> кстати, я тут позапускал... квадратные скобки ни на что не влияют. проблема была только в двойных кавычках

Я предположил что он думает, что это массив.
Хотя ты прав, надо было позапускать.

2020-11-20 08:58 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/exception/IncomingMessageCheckException.java
> +public class IncomingMessageCheckException extends RuntimeException {
Изначально был момент по входящему.
MessageValidationException.

2020-11-20 09:19 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +	private int chatId;
Да, не прочёл описание.
Было long прочёл, что integer и поменял.
Может быть больше 32 бита, но не более 52 бита, надо long.
Зачем тогда пишут integer, чтоб просто указать что это целое?

2020-11-20 09:19 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	 * @param token          Строка с токиеном.
Копипаст.

2020-11-20 09:22 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		checkObject(receivedObject);
Object это не Java Object, а как объект в русском.
Надо придумать синоним тогда, а то точно вводит в заблуждение.

2020-11-20 09:23 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		JSONObject messageObject = receivedObject.getJSONObject("message");
Object это не Java Object, а как объект в русском.
Надо придумать синоним тогда, а то точно вводит в заблуждение.

2020-11-20 09:29 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject) {
receivedObject это для внутри в методе чтоб было понятно было что это именно полученный методом объект.
Я же много кода не видел, если просто json информативно и достаточно сделаю так.

2020-11-20 09:31 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject, String objectName) {
Да точно, key.
Просто нас всё время везде учат чтоб название должно говорить, что оно значит.
А по факту надо абстракно думать.

2020-11-20 10:31 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +	private int chatId;
интеджер может отличаться в разных языках программирования. например, unsigned integer - беззнаковый инт. те же 32 бита, но смещены и начинаются от 0
но в джаве инты не такие

2020-11-20 10:33 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		checkObject(receivedObject);
но ты же передаешь в этот метод переменную с названием объекта. поэтому конкретно в этой ситуации - можно просто `validate(someObject)`, читабельность не ухудшится, я думаю

2020-11-20 10:33 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		JSONObject messageObject = receivedObject.getJSONObject("message");
ну я и предложил вариант: `messageBlock`

2020-11-20 10:39 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject, String objectName) {
ну не то чтобы абстрактно... тогда бы у нас все и везде было бы обджектами)
по названию переменной должно быть понятно что в ней. и да, понятно, что там будет какой-то объект в большинстве случаев :) это если пишется какой-то абстрактный метод, с дженериками там, где ты понятия не имеешь что там за объект будет - тогда может и оправданно... но честно говоря, я не видел ни одного такого метода, где переменные были бы названы просто как `object`. все-таки даже там стараются придумывать что-то понятнее

2020-11-20 13:37 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +	private int chatId;
Ясно, типа как char.

2020-11-20 15:35 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	 * @param token       Строка с токиеном.
Откорректировал.

2020-11-20 15:37 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	 * @param token          Строка с токиеном.
Откорректировал.

2020-11-20 15:38 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerService.java
> +	 * @param receivedObject JSON объек.
Откорректировал.

2020-11-20 15:41 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	 * @param token          Строка с токиеном.
Изменил.

2020-11-20 15:42 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	 * @param receivedObject JSON объек.
Изменил.

2020-11-20 17:16 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	 * @param receivedObject JSON объек.
Done.

2020-11-20 17:57 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/exception/IncomingMessageCheckException.java
> +public class IncomingMessageCheckException extends RuntimeException {
Сделал MessageValidationException.

2020-11-20 18:02 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/modelbot/Message.java
> +	private int chatId;
Сменил на long.

2020-11-20 18:18 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		checkObject(receivedObject);
Селал validate(json).

2020-11-20 18:25 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		JSONObject messageObject = receivedObject.getJSONObject("message");
Класс!

2020-11-20 18:27 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject) {
Done.

2020-11-20 18:34 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isNull(JSONObject receivedObject, String objectName) {
Сделал.
Верно. Более понятно: json, key.

2020-11-20 18:35 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void isEmpty(JSONObject receivedObject, String objectName) {
Сделал.
Аналогично в других замечаниях.

2020-11-20 18:35 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +	private void hasObject(JSONObject receivedObject, String objectName) {
Сделал.
Аналогично в других замечаниях.

2020-11-20 18:35 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +			throw new IncomingMessageCheckException("The incoming object cannot be null.");
Сделал.
Аналогично в других замечаниях.

2020-11-20 19:25 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +			exceptionAnswer = exceptionAnswer.replaceAll("\\[\"", " '");
Нашёл метод классный в либе **org.json.JSONObject** (вроде нам хорошо подходит):
**JSONObject._quote_**(exceptionAnswer)

Работает (правда немного по своему ))), но работает):
{"error":"JSONObject[\"chat\"] not found."}

**Но, работает класс!**

2020-11-20 19:54 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> + * Класс обработки сообщений пришедших на вебхук определённого бота.
Может так:

_Класс ждёт оповещения от webhook, при получении сообщения перенаправляет их в сервис для обработки._

2020-11-20 19:57 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	 * Слушает запросы вебхука бота и предаёт полученные сообщения и токен сервису.
Может так:

_Ожидает оповещения от webhook, при получении сообщения передаёт их в сервис для обработки._

2020-11-23 16:47 UTC, spasynkov approved these changes
все круто, я доволен :)
есть мелкие замечания, но то уже мелочи реально. их можно и потом уже поправить

2020-11-23 16:47 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	public String receiveAndProcessMessage(@PathVariable("token") String token, @RequestBody JSONObject requestBody) {
кстати, если значение аннотации PathVariable такое же, как и название переменной, и такое же, как собственно и нужная нам часть пути - то можно просто написать `@PathVariable String token` и спринг сам догадается, что этот тот токен, что в части пути там указан.
это править не надо, просто на будущее говорю, оно так меньше повторов будет :) особенно когда сразу несколько PathVariable принимать будет

2020-11-23 16:47 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		hasObject(json, "message");
методы, у которых название начинается на is или has - это обычно методы, которые возвращают boolean

конкретно тут лучше бы сделать ensureHasObject. тогда если объекта не оказалось - то и "убедиться" в этом не получилось и потому и исключение :)

хотя, в принципе, это можно сказать и про методы isNull и isEmpty, что они тоже на булеановские "похожи"...) и что лучше тоже как-то придумать типа assertNotNull assertNotEmpty... или ensure вместо assert... но да, лучше сделать так, что по названию было понятно, что мы проверяем, что объект именно НЕ нулл и НЕ пустой :) потому что сейчас по названиям твоих методов может сложиться впечатление, будто мы проверяем в них, что объект пустой или нулл :)

в общем, это тонкости уже такие... но чем меньше вопросов возникает у "читателя" твоего кода, чем меньше ему приходится заходить в твои методы и смотреть что они делают - тем лучше :)

2020-11-23 16:55 UTC, MrErgos approved these changes

2020-11-23 16:56 UTC, merged

2020-11-23 16:57 UTC, klimenkoMA approved these changes

2020-11-23 19:36 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/service/WebhookHandlerServiceImpl.java
> +		hasObject(json, "message");
Хорошо.

2020-11-23 19:36 UTC, babinvas commented on src/main/java/com/example/telegrambotinsurance/controller/WebhookHandlerController.java
> +	public String receiveAndProcessMessage(@PathVariable("token") String token, @RequestBody JSONObject requestBody) {
Понял.