Close #21 funtion to use different keyboards
spasynkov/telegram-bot-insurance pull request #24
Opened 2020-11-20 12:47 UTC by MrErgos

2020-11-21 11:15 UTC, spasynkov commented
![image](https://user-images.githubusercontent.com/14253682/99875776-d9c02a00-2bfa-11eb-9a00-b7882b0e02f7.png)
я так понял, тут только два коммита?
возможно стоило бы по каждому отдельному методу - отдельный коммит. типа, "добавил такую-то клавиатуру", "добавил другую клавиатуру", "добавил фичу удаления клавиатуры".
а просто что добавил 100500 методов - не очень информативное название коммита :)

2020-11-21 13:03 UTC, spasynkov requested changes
много опечаток
много чего можно заменить ломбоком
много повторов кода (складывалось впечатление, что прям классы целиком одинаковые)

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/exception/ButtonFormatException.java
> +public class ButtonFormatException extends RuntimeException{
конструктора по умолчанию не будет?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/exception/MethodNotSupported.java
> +public class MethodNotSupported extends Exception{
было бы неплохо тут какой-то джавадок добавить, потому что просто глядя на класс - не совсем понятно про какой метод идет речь. джавовский или телеги

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * Вы должны использовать ровно одно из необязательных полей.
ровно одно или мининмум одно? ты в чате вроде писал, что минимум одно

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * HTTP или tg: // url, который открывается при нажатии кнопки
я б написал, что это урл колбека/вебхука, который выполнится при нажатии на эту кнопку

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * URL-адрес HTTP, используемый для автоматической авторизации пользователя.
авторизации где? если пользователю приходит такая кнопка - значит он как минимум уже авторизирован в телеге и зашел под своим аккаунтом и только после этого получил это сообщение с клавиатурой

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * Данные для отправки боту в ответном запросе при нажатии кнопки, 1-64 байта
че-то не понял чем отличается от переменной урл. и зачем это надо.
может стоит чуть детальнее расписать этот момент

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 *  когда они в данный момент находятся в приватном чате с ним.
я прочитал и ничего не понял :)
может стоит написать как-то попроще? или наоборот, детальнее

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * - удобно для выбора из нескольких вариантов.
тоже не совсем понял что тут происходит и чем отличается от предыдущего.
как я понял, в поле ввода текста вставится имя бота и ... непонятно что и зачем еще.

и что такое "встроенный режим" - тоже непонятно.
я понимаю, что ты просто описание из документации взял и перевел) но стоило не просто перевести, но и прочитать что получилось и написать это же, но понятнее :)

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 *  Кнопка этого типа всегда ДОЛЖНА быть первой в ряду.
что за первый ряд? только здесь впервые слышу об этом, может стоило бы подетальнее написать что за первый ряд)

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 *  Кнопка этого типа всегда ДОЛЖНА быть первой в ряду.
аналогично

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	}
это все можно заменить ломбоковскими аннотациями

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	public interface Builder{
в джаве уже есть такой интерфейс вроде. он там типизированный возвращаемым типом

а еще у ломбока есть такая аннотация
https://projectlombok.org/features/Builder

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButtonBuilder.java
> +public class InlineKeyboardButtonBuilder implements InlineKeyboardButton.Builder {
какая-то сложная реализация получилась.
а попроще - не?

обычно это делается просто внутренним классом. а у тебя и интерфейс отдельный, и этот класс, и внутренний

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	 * Массив массивов кнопок
но ведь у тебя не массив массивов, а список списков :)
массив массивов - это если бы было `InlineKeyboardButton[][]`

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	private List<List<InlineKeyboardButton>> inline_keyboard = new ArrayList<>();
почему именно `ArrayList`, а не например `LinkedList`?
чем `ArrayList` тут лучше?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	public void addKeyboardRow(){
я так понимаю, этот метод каждый раз добавляет новый ряд в конце
так может его и назвать `newRow()`
принципиальной разницы нет, конечно, работать и так будет. но просто оно при вызове метода этого будет понятнее если просто `newRow()` будет, нет?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +		}
кек, а что тут происходит? :)

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	 * Метод добавляет переданную кноку в ряд под переданным числом (отсчет начинается от 0)
может как-то типа "добавляет в последний ряд на определенную позицию"?

к тому же в джавадоках между описанием и списком параметров принято пустую строку оставлять (ну со звездочкой)

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	 * @param button
а че не описал что за параметры?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	 * Метод добавляет переданную кноку в ряд под переданным числом (отсчет начинается от 0)
ага, понял, потому что не в последний ряд добавляет, а в любой. я думаю есть смысл сделать возможность добавления и в последний ряд.

да и кнопку не на определенную позицию добавляет, а в конец.

давай будет один метод, который добавляет на определенный ряд, на определенную позицию
один метод, который добавляет в последний ряд на определенную позицию
и еще один метод, который добавляет в последний ряд на последнюю позицию
все методы перегружены

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +			inline_keyboard.get(number).add((InlineKeyboardButton) button);
а зачем этот каст, и отдельный кетч, если ты можешь просто методу сказать, что он будет принимать только определенные кнопки?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/Keyboard.java
> +	void addButton(int number,Button button);
описал правки чуть выше, в имплементации

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardButton.java
> +public class KeyboardButton implements Button{
это же кнопки для ReplyKeyboard? они же не подходят для InlineKeyboard? так может и класс поточнее назвать?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardButton.java
> +	 * Предлагает пользователю отпрвить свой номер телефона
отпрвить

я бы написал так, что при нажатии на кнопку - отправляется номер телефона пользователя

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardButton.java
> +	 * Предлагает пользователю отпрвить свою геолокацию
отпрвить 

аналогично, не уверен, что предлагает, думаю, что просто отправляет и все

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardButton.java
> +	}
аналогично, для этого есть ломбок

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardsService.java
> +	}
ну это точно не айс.
убрать клавиатуру можно будет только с текстом Тест? и только для определенного чата?
этот метод должен возвращать такой "объект клавиатуры", который бы удалял клавиатуру.

при этом, как и любую другую клавиатуру мы могли бы прикрепить к какому-то (любому) сообщению. и, конечно же, отправлять в любой чат могли бы

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardsService.java
> +				.setText("2").setUrl("https://core.telegram.org/bots/api#inlinekeyboardbutton").build());
лучше разбить на создание кнопки, и установку кнопки в клавиатуру

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardsService.java
> +	}
вообще, я совсем не так видел этот сервис :)

я думал, это и будет билдер, при помощи которого, можно будет "строить" нужную клавиатуру.
то, какая это будет клавиатура, с какими кнопками - не зависит от сервиса. это будет сам бот создавать нужную для него клавиатуру. сервис должен лишь давать возможность ее создать удобно.
потому что для другого бота с другим функционалом - этот сервис не подойдет вообще никак :) потому что тут захардкодены определенные кнопки и определенная конфигурация клавиатуры :)

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/LoginUrl.java
> +	 * Текст кнопки в перенаправленных сообщениях.
что за перенаправленные сообщения? и что за кнопка в них с этим текстом?
похоже на кривой перевод :) или на перевод вне контекста

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/LoginUrl.java
> +	 * Добавляемые данные такие же, как описано в разделе Telegram API «Получение данных авторизации». ->
вообще не понимаю зачем ты это все переводил, если в документации там все на английском написано (и джавадоки и все комментарии принято писать на английском).
да и копипастить все это не было смысла, достаточно было просто урлы на определенные места в документации покидать и все. ну типа 
https://core.telegram.org/bots/api#loginurl

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/LoginUrl.java
> +	 * Текст кнопки в перенаправленных сообщениях.
я так понимаю, что если пользователь решит "переслать" это сообщение с кнопкой кому-то другому - то как будет выглядеть этот текст при редиректе. надо потестить и написать по-человечески.
вообще, стоило бы все эти возможности потестить, и написать по-понятному это все :)
ну или просто пооставлять ссылки на документацию

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/LoginUrl.java
> +public class LoginUrl {
вообще сомневаюсь, что мы будем этим вообще когда-нибудь пользоваться.
это для того, чтобы на нашем сайте можно было авторизировать пользователей телеграмма
это как и с играми, и с пейментом. можно было оставить просто пустым

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/LoginUrl.java
> +	}
тоже ломбок

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	 * Массив массивов кнопок
снова же не массив

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	 * Подгоняет ращмер клавиатуры под количество рядов
ращмер

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	 * (если false, то клавиатура будет как стандартная у пользователя)
что такое "стандартная у пользователя"?

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	 * Если true, то после ипользования клавиатура скроется,
ипользования

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	}
тоже не обязательно

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	 * Метод добавляет одну кноку с переданным текстом в ряд под переданным числом
кноку

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	}
где-то я это все видел уже

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	}
точнее, вот это

2020-11-21 13:03 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	}
и это просил уже заменить на ломбок...
у тебя точно нет повторов кода?

2020-11-21 13:03 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsServiceTest.java
> +class KeyboardsServiceTest {
тоже, поскольку сервис не тот, то и тесты эти отпадают

2020-11-21 18:05 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * Вы должны использовать ровно одно из необязательных полей.
![image](https://user-images.githubusercontent.com/66214678/99884193-4f4cea00-2c3d-11eb-8d34-1c80cae7be63.png)

2020-11-22 14:25 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +			inline_keyboard.get(number).add((InlineKeyboardButton) button);
Это так нужно, так как я всё сделал через интерфейсы, а если поменяю, то ошибка

2020-11-22 14:27 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardButton.java
> +	 * Предлагает пользователю отпрвить свой номер телефона
Там предлагается пользователю

2020-11-23 17:26 UTC, klimenkoMA submitted a review, later dismissed

2020-11-23 17:51 UTC, spasynkov requested changes
по архитектуре
я считаю, что ReplyKeyboardRemove - это тоже как бы клавиатура. я помню у нас был разговор об этом и я тогда сказал, что все ок, оставляй отдельным классом... но сча вот немного пересмотрел, когда увидел картину целиком.

я вижу, что все, все методы внутри `InlineKeyboardMarkup` - они точно такие же, как и в `ReplyKeyboardMarkup`. и переменнаыя тоже отличается только названием и типом кнопок (у тебя есть интерфейс `Button`, но ты типизировал клавиатуру конкретным типом кнопки? считаю это неправильным вот как-раз потому, что тебе пришлось из-за этого делать две по своей сути одинаковые раскладки клавиатур, потому что у них там в одной переменной тип кнопок отличается)

в общем, я предлагаю:

- сделать интерфейс клавиатуры - маркером (без методов)
- пометить `ReplyKeyboardRemove` тоже этим маркером
- создать абстрактный класс типа `AbstractKeyboard` куда вынести все-все общее из классов `InlineKeyboardMarkup` и `ReplyKeyboardMarkup` (`InlineKeyboardMarkup` скорее всего вообще получится пустым)
- чтобы вообще по-красоте сделать - воспользуйся дженериками там, где не сможешь выкрутиться обычным наследованием.

с кнопками вроде все ок.
а вот `KeyboardsService` почему-то оказался не в пакете со своими братьями-сервисами, а с клавиатурами :)
и еще, я не вижу куда пропали все билдеры

в сервисе там у тебя везде используется JSONObject, который не подключен.
смержи дев к себе, там уже правки Василия есть и библиотека подключена. тогда починятся проблемы с импортами и джейсонами

тесты пока не запускал, так как надо переработать структуру классов

2020-11-23 17:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	 * Вы должны использовать ровно одно из необязательных полей.
все верно. вот скрин из документации, где об этом сказано
![image](https://user-images.githubusercontent.com/14253682/99990702-d379ab80-2dbc-11eb-9b05-f6985a550bec.png)

2020-11-23 17:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardButton.java
> +@AllArgsConstructor
я б еще добавил бы NoArgsConstructor
это правило хорошего тона оставлять конструктор без параметров. многие фреймворки создают объекты наших классов именно используя конструкторы без параметров.
и если его не будет - то что-то может работать некорректно

2020-11-23 17:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	private Boolean selective = null;
а почему нулл, а не фолс, как в других?

2020-11-23 17:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/KeyboardsService.java
> +import org.json.JSONObject;
один импорт не используется, а второй импорт - вообще все ломает и проект не компилируется даже :) такое заливать - это очень плохо. когда после твоих коммитов весь проект у всех перестанет компилироваться и запускаться)
я понимаю, что это просто не подчистил, но будь внимательнее. или настрой в идее автоимпорты и  автоочистку импортов, чтобы вообще не париться об этом

2020-11-23 17:51 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	public void addButton(int positionInTheRow, int rowPosition,Button button){
с названиями переменных тут что-то не оч. они очень похожи.
давай может `rowNumber`?

2020-11-24 10:43 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardButton.java
> +@AllArgsConstructor
Эта кнопка не может быть без текста, поэтому и нет конструктора без параметров

2020-11-26 19:23 UTC, spasynkov requested changes
не знаю что это за пулл-риквест такой...
я переключаюсь на твою ветку - у меня все красное
естественно, сервер не стартует.
код, который "ломает" проект, при котором проект перестает компилироваться даже, не то что работать - никогда не будет залит.
если тебе не хватает библиотеки - смержь ветку дев к себе в ветку и все станет ок. но отправлять нерабочий код на ревью - это неправильно. нерабочий он потому что он даже не запускается :)

к тому же по архитектуре никаких изменений не вижу. я просил вынести общую логику в абстрактный класс

2020-11-26 19:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsServiceTest.java
> +		System.out.println(jsonObject.toString());
прикольно, но это не ассерт :)

то, что ошибка будет просто выведена на экран, но тест будет пройден - это не так должно работать.
если ошибка - значит и тест не должен проходить
сейчас же эти тесты ничего не проверяют. они используют основной код, да, но тест этот не говорит ничего о том работает ли основной код или нет

2020-11-26 19:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsServiceTest.java
> +	}
аналогично. тут даже на экран ничего не выводится.
с таким же успехом можно было написать тест
```
@Test
void removeKeyboard(){
	int a = 15 + 18;
	a *= 42;
}
```
такой тест тоже что-то делает, но по сути - ничего :)

2020-11-26 19:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsServiceTest.java
> +	}
аналогично

2020-11-26 19:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsServiceTest.java
> +	}
ну и тут. в общем, с тестами - беда

2020-11-26 19:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	public void addButton(int positionInTheRow, int rowPosition,Button button){
а тут почему ничего не ответил и не поправил?

2020-11-26 19:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardMarkup.java
> +	private List<List<InlineKeyboardButton>> inline_keyboard = new ArrayList<>();
и тут без ответа оставил

2020-11-30 09:32 UTC, klimenkoMA requested changes

2020-11-30 09:32 UTC, klimenkoMA commented on src/main/java/com/example/telegrambotinsurance/service/KeyboardsService.java
> +		System.out.println(jsonObject.toString());
Вот здесь можно заменить System.out.println(jsonObject.toString()) на LOGGER.debug()

2020-11-30 09:32 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +		System.out.println(jsonObject.toString());
Можно заменить System.out.println(jsonObject.toString() на LOGGER.debug()

2020-11-30 09:32 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +}
Не уверен, что тесты без использования Assertion правильные. По аналогии с тестированием записи в БД: можно проверить, появился ли список с клавиатурами, сколько в этом списке элементов, уменьшается ли список при удалении клавиатуры, увеличивается ли список кнопок  при добавлении кнопок и т.д. Ответ от АПИ тоже можно проверить - вернулся ли не нулевой JSONObject, получен ли ответ "ок", "200"

2020-11-30 09:46 UTC, MrErgos commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +		System.out.println(jsonObject.toString());
Это один раз так сделал, и уже убрал, это не нужно для теста)

2020-11-30 09:46 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/service/KeyboardsService.java
> +		System.out.println(jsonObject.toString());
Это один раз так сделал, и уже убрал, это не нужно для теста)

2020-11-30 09:47 UTC, MrErgos commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +}
Я сделал тесты, пока они не работают, когда ты завершишь они заработают

2020-12-02 20:52 UTC, spasynkov requested changes
есть еще пару замечаний

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/Keyboard.java
> +public interface Keyboard {
может лучше тут назвать не клавиатурой, а `ReplyMarkup`?
ведь получается, что клавиатуры всего две. еще одна фигня для отмены клавиатуры, ну и форс-реплай, который к клавиатуре тоже как бы не относится ни разу

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	protected static final Logger LOGGER = LoggerFactory.getLogger(AbstractKeyboard.class);
а почему протектед?
да и как может быть протектед вместе со статик?)
ведь статические методы и переменные не могут быть унаследованы. а значит и модификатор доступа не корректный

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	private String exceptionMessage = "Row under this number doesn't exist";
идея подсвечивает же желтым ворнинг тебе :) нажми Alt+Enter посмотри что предложит

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +		}
а зачем здесь трай-кетч? если исключение не кидается.

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	}
тут у тебя дублирование кода. это не очень хорошо.
обычно в таких случаях просто вызывают перегруженный метод и передают в него нужный параметр

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	}
аналогично и тут

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardButton.java
> +@AllArgsConstructor
ну ок, согласен :)

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardButton.java
> +	private Boolean request_location = false;
ок, а как мне поменять значение на тру?

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardButton.java
> +	private static final Logger LOGGER = LoggerFactory.getLogger(ReplyKeyboardButton.class);
не понимаю зачем тут логгер нужен

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	}
а зачем этот метод, если ты проставил аннотацию `@Getter`?
может ты тут хотел добавить какую-то другую аннотацию для этого геттера? :)

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	private Boolean selective = null;
аналогично и тут. не вижу как можно было бы установить какую-то из этих переменных в `true`

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/Keyboard.java
> +
давай добавим сюда метод `toJson()`

2020-12-02 20:52 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/service/KeyboardsService.java
> +public class KeyboardsService {
а почему все-таки решил через сервис сделать?
вроде ж договаривались просто через билдер

2020-12-02 20:52 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +		Assertions.assertEquals(response.optString("ok"), "true", "Wrong response from telegram servers, field: ok = false");
мне кажется или этот код встречается чуть ли не в каждом тесте по тестированию отправки сообщений?

может давай как-то вынесем общую логику в какой-то общий класс?
наследование тестам еще может понадобиться, поэтому можем такую штуку провернуть в интерфейсе (дефолтный метод).
хотя лучше наверное создать какой-то класс типа TestUtils и там просто статический метод такой сделать. типа `checkTelegramResponseAfterSendingMessage(JSONObject response)`

2020-12-02 20:52 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +}
@klimenkoMA этот момент вроде поправили, да?

2020-12-03 16:48 UTC, klimenkoMA approved these changes, later dismissed

2020-12-03 16:48 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/service/KeyboardsServiceTest.java
> +}
Да, теперь тесты работают как надо

2020-12-04 11:33 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/keyboards/Keyboard.java
> +public interface Keyboard {
Можно но лучше просто Markup, т.к. есть inline

2020-12-04 11:35 UTC, MrErgos commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	protected static final Logger LOGGER = LoggerFactory.getLogger(AbstractKeyboard.class);
Исправил, просто осталось с тестов над логгером(

2020-12-15 06:23 UTC, spasynkov requested changes
еще несколько замечаний осталось

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +		int rowNumber = keyboard.size()-1;
я смотрю этот кусок кода у тебя дважды встречается в разных местах
`keyboard.size()-1`
так может сделать метод `getLastRowIndex()` и вызывать его в этих местах? :)

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	}
ты ж вроде вынес этот функционал в интерфейс `Markup`?
зачем тогда здесь оставил? :)

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	private Boolean selective = null;
так и не увидел ответа

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	private Boolean selective = null;
переименуй эти переменные так, как принято в джаве. а то у тебя методы билдеров тоже такие кривые получились :)

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +	}
зачем, если точно такой же метод есть в Markup, с точно такой же реализацией

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> + 	public static abstract class AbstractKeyboardBuilder<T> {
а зачем тут дженерик?
без него ведь точно так же работает :)
то у меня в реализации была переменная instance и там да, в зависимости от того, что за билдер-наследник - то и тип у этой переменной был разный.

у тебя же здесь дженерик нужен только для того, чтобы починить при его помощи баг с тем, что если методы билдера-наследника вызывать после какого-то из методов из абстрактного билдера - то там ошибка. потому что абстрактный билдер возвращает билдер, но типа `AbstractKeyboardBuilder`, у которого нет специализированных методов для разных клавиатур

тут мог бы воспользоваться дженериком.
типа, в названии класса указать, что класс будет использовать тип Т, который будет одним из подтипов класса `AbstractKeyboardBuilder`
ну и соответственно методы твоего билдера будут возвращать не `AbstractKeyboardBuilder`, а вот этот вот Т

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> + 	public static abstract class AbstractKeyboardBuilder<T> {
ааа, хотя не.
так тоже не оч.
даже хуже, чем у тебя сейчас сделано. потому что кастовать приходится к объекту
![image](https://user-images.githubusercontent.com/14253682/102175181-ab570700-3ea7-11eb-9f1d-741f4894144f.png)

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> + 	public static abstract class AbstractKeyboardBuilder<T> {
в общем, давай так.
оставляем как сделано у тебя сейчас, пофиг, что при другом порядке методов у нас все ломается(

только пусть твой билдер расширяет соответствующий типизированный интерфейс `Builder<T>`. у спринга он есть, или у апач-комонс, там увидишь. тогда наш метод `build()` будет возвращать этот вот тип данных.

ну или почитай вот эту статью, может и выйдет сделать так, как я изначально хотел сделать :)
https://habr.com/ru/post/125846/

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/AbstractKeyboard.java
> +		public abstract T build();
если проимплементишь интерфейс `Builder<T>` - то и этот метод будет тут не нужен, так как он уже объявлен в интерфейсе

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/InlineKeyboardButton.java
> +	public static class InlineKeyboardButtonBuilder {
а вот тут мог бы коммент и оставить, что здесь переопределяется нужный нам метод из ломбоковского билдера :) потому что через месяц уже забудешь почему тут это так сделано :)

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardButton.java
> +				throw new IllegalStateException("Cannot send 'request_contact' and 'request_location'.");
не совсем понятное сообщение об ошибке. первым вопросом у меня в голове будет - почему не получилось отправить? проблемы с отправкой?
а потом окажется, что совсем не туда копал бы, потому что проблемы с формированием клавиатуры :)

добавь наверное, что должно быть отправлено что-то одно

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +	private Boolean selective = null;
и до сих пор не понимаю почему нулл :)

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +		public ReplyKeyboardBuilder setOne_time_keyboard(Boolean one_time_keyboard) {
сделай названия методов по феншую чтоб :) без нижнего_подчеркивания

2020-12-15 06:23 UTC, spasynkov commented on src/main/java/com/example/telegrambotinsurance/keyboards/ReplyKeyboardMarkup.java
> +		public ReplyKeyboardBuilder setOne_time_keyboard(Boolean one_time_keyboard) {
да и переменные тоже. чтобы и геттеры-сеттеры тоже нормальные сгенерились.
а чтобы в джейсон попало как тебе надо - то это аннотацией укажи

2020-12-15 06:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsBuilderTest.java
> +	SendRequestsService sendRequestsService;
там как Михаил доделает свою таску - надо будет тут переделать чтобы через его сервис отправлялись сообщения.
добавь тут тудушку пока что, чтоб не забыть

2020-12-15 06:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsBuilderTest.java
> +				.setResize_keyboard(true)
вот про это место я там выше писал. сейчас оно работает только если эти методы вызваны в самом начале, до того, как вызовется первый из методов из `AbstractKeyboardBuilder`. это не очень правильно, так как пользователи нашего класса будут вынуждены помнить о том, что вот конкретно в этом случае - надо соблюдать порядок вызова методов. и поверь, постоянно будут об этом забывать и ругать такую библиотеку :)

2020-12-15 06:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsBuilderTest.java
> +				"{\"chat_id\":-386295340, \"text\":\"Starter menu\", \"reply_markup\":" + JSONKeyboard.toString()+"}");
вынеси номер чата в константы теста. он же используется в разных методах

2020-12-15 06:23 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/keyboards/KeyboardsBuilderTest.java
> +	void checkingBuildsViaIndexes() {
как я понял, ты в этом тесте проверяешь, что джейсон не пустой?
давай чуть детальнее проверять тут.
например, сначала собрать клавиатуру с индексами
потом собрать другой объект такой же клавиатуры, но уже без индексов, а в нужном порядке

к тому же этот тест проверяет 3 разных случая. так что логичнее было бы его азбить на 3 отдельных теста

и еще добавить по отдельному тесту на каждый из методов `addRow()` и `addButton()`, где проверить, что они добавляют в правильное место списка

2020-12-25 15:49 UTC, spasynkov approved these changes

2020-12-25 15:50 UTC, merged