#25 changed library in SendRequestsService class and SendRequestsServ…
spasynkov/telegram-bot-insurance pull request #26
Opened 2020-11-25 18:41 UTC by klimenkoMA

…iceTest class,

changed assertions in sendGet() and sendPost()

2020-11-26 18:55 UTC, spasynkov requested changes
тесты не работают, это первое и самое главное

второе - тесты менять не надо было. библиотеку поменять, конечно, но структуру тестов - не надо было :) и особенно нельзя логику тестов подгонять под свой результат (хоть этого и не было, но все же)

2020-11-26 18:55 UTC, spasynkov commented on src/test/java/com/example/telegrambotinsurance/service/SendRequestsServiceTest.java
> +		Assertions.assertEquals(response.getString("ok"), "true", "Wrong response from telegram servers, field: ok = false");
опача :)
а зачем тесты трогал?)
когда пишешь основной код - тесты не должны меняться :)
проблема в том, что тестовые методы не должны кидать никаких исключений. если в тесте произошло исключение - значит что-то в нем не работает.
если невозможно достать стрингу - значит тест должен завалиться, а не программа целиком :)
мавен, например, когда билдит проект - он тоже запускает тесты. и билд не должен валиться из-за того, что в тестах **_ПРОВЕРЯЕМОЕ_** исключение не проверили и не обработали :)

2020-11-29 18:19 UTC, klimenkoMA commented on src/test/java/com/example/telegrambotinsurance/service/SendRequestsServiceTest.java
> +		Assertions.assertEquals(response.getString("ok"), "true", "Wrong response from telegram servers, field: ok = false");
Принял, исправлю

2020-12-01 16:22 UTC, spasynkov approved these changes
вроде ок

2020-12-01 16:23 UTC, merged