Task1 create logging level
spasynkov/telegram-bot-insurance pull request #5
Opened 2020-10-14 19:01 UTC by klimenkoMA

I finished the first task, set the logging level, the date format in messages, and the web server port
Close #1

2020-10-14 21:19 UTC, spasynkov requested changes
почти все как надо, только название пакета надо поправить

2020-10-14 21:19 UTC, spasynkov commented on src/main/resources/application.properties
> +logging.level.org.example.telegrambotinsurance=DEBUG
у нас название пакета не такое :) поправь, пожалуйста, а то работать не будет :)

2020-10-15 04:34 UTC, klimenkoMA commented on src/main/resources/application.properties
> +logging.level.org.example.telegrambotinsurance=DEBUG
Принял, смотрю

2020-10-15 05:22 UTC, klimenkoMA commented on src/main/resources/application.properties
> +logging.level.com.example.telegrambotinsurance=DEBUG
```suggestion
logging.level.com.example.telegrambotinsurance=DEBUG
```

2020-10-15 08:02 UTC, spasynkov approved these changes

2020-10-15 08:02 UTC, merged